openapi: 3.0.0
info:
  title: Addition API
  description: The public facing API of our internal addition service
  version: 1.0.0
servers:
  - url: https://localhost:8443
    description: The server we need you to implement
paths:
  /add:
    post:
      description: Can optionally respond synchronously with the calculated result from the internal Kafka topic
      requestBody:
        description: The specified calculation request
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CalculationRequest'
      parameters:
        - in: query
          name: syncResult
          required: false
          schema:
            type: boolean
          description: Specifies if the result should be provided in the response
      responses:
        '200':
          description: The response for the calculation request
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/CalculationResponse'
  /list-results:
    get:
      description: Responds with a list of all calculation results from the internal Kafka topic
      responses:
        '200':
          description: A JSON array of user names
          content:
            application/json:
              schema: 
                type: array
                items:
                  allOf:
                    - $ref: '#/components/schemas/AsyncId'
                    - $ref: '#/components/schemas/CalculationResult'
components:
  schemas:
    AsyncId:
      type: string
      example: 56d583ed-3e70-4e44-b5ce-d011e5a34326
      description: The id of the requested calculation
    CalculationRequest:
      type: object
      properties:
        numberOne:
          type: number
          example: 4
        numberTwo:
          type: number
          example: 4.5
      required:  
        - numberOne
        - numberTwo
    CalculationResponse:
      type: object
      properties:
        asyncId:
          $ref: '#/components/schemas/AsyncId'
        result:
          $ref: '#/components/schemas/CalculationResult'
      required:
        - asyncId
    CalculationResult:
      type: object
      properties:
        numberOne:
          type: number
          example: 4
        numberTwo:
          type: number
          example: 4.5
        result:
          type: number
          example: 8.5
      required:  
        - numberOne
        - numberTwo
        - result
